/* Review Table */
DROP TABLE IF EXISTS review;

CREATE TABLE review(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT,
  rating INT,
  date BIGINT,
  summary VARCHAR,
  body VARCHAR,
  recommend VARCHAR, /* 0 for false, 1 for true */
  reported VARCHAR, /*  0 for false, 1 for true */
  reviewer_name VARCHAR,
  reviewer_email VARCHAR,
  response VARCHAR,
  helpfulness INT DEFAULT 0
);
-- review id int references review (review_id) <- for foreign keys

COPY review
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/CSVs/reviews.csv'
DELIMITER ','
CSV HEADER;

------------------------------------------------------------------------
/* Product Table */
DROP TABLE IF EXISTS product;

----------------------------------------------------------------------
/* Photo Table */
DROP TABLE IF EXISTS reviews_photos;

CREATE TABLE reviews_photos(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id INT REFERENCES review (id),
  url VARCHAR
);

COPY reviews_photos
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/CSVs/reviews_photos.csv'
DELIMITER ','
CSV HEADER;


------------------------------------------------------------------------
/* Characteristics Table */
DROP TABLE IF EXISTS characteristics;

CREATE TABLE characteristics(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT,
  name VARCHAR
);

COPY characteristics
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/CSVs/characteristics.csv'
DELIMITER ','
CSV HEADER;


------------------------------------------------------------------------
/* Meta Table */
DROP TABLE IF EXISTS meta;

CREATE TABLE meta(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  characteristic_id INT REFERENCES characteristics (id),
  review_id INT REFERENCES review (id),
  value INT
);

COPY meta
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/CSVs/characteristic_reviews.csv'
DELIMITER ','
CSV HEADER;