/* Review Table */
DROP TABLE IF EXISTS review;

CREATE TABLE review(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT,
  rating INT,
  date BIGINT,
  summary VARCHAR,
  body VARCHAR,
  recommend VARCHAR, /* 0 for false, 1 for true */
  reported VARCHAR, /*  0 for false, 1 for true */
  reviewer_name VARCHAR,
  reviewer_email VARCHAR,
  response VARCHAR,
  helpfulness INT DEFAULT 0
);
-- review id int references review (review_id) <- for foreign keys

COPY review
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/reviews.csv'
DELIMITER ','
CSV HEADER;

------------------------------------------------------------------------
/* Product Table */
DROP TABLE IF EXISTS product;

CREATE TABLE product(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR,
  slogan VARCHAR,
  description VARCHAR,
  catergory VARCHAR,
  default_price INT
);

COPY product
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/product.csv'
DELIMITER ','
CSV HEADER;


----------------------------------------------------------------------
/* Photo Table */
DROP TABLE IF EXISTS photos;

CREATE TABLE photos(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id INT,
  url VARCHAR
);

COPY photos
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/reviews_photos.csv'
DELIMITER ','
CSV HEADER;


------------------------------------------------------------------------
/* Characteristics Table */
DROP TABLE IF EXISTS characteristics;

CREATE TABLE characteristics(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT,
  name VARCHAR
);

COPY characteristics
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/characteristics.csv'
DELIMITER ','
CSV HEADER;


------------------------------------------------------------------------
/* Meta Table */
DROP TABLE IF EXISTS meta;

CREATE TABLE meta(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  characteristic_id INT,
  review_id INT,
  value INT
);

COPY meta
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/characteristic_reviews.csv'
DELIMITER ','
CSV HEADER;