/* Review Table */
DROP TABLE IF EXISTS review;

CREATE TABLE review(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT,
  rating INT,
  date BIGINT,
  summary VARCHAR,
  body VARCHAR,
  recommend VARCHAR, /* 0 for false, 1 for true */
  reported VARCHAR, /*  0 for false, 1 for true */
  reviewer_name VARCHAR,
  reviewer_email VARCHAR,
  response VARCHAR DEFAULT NULL,
  helpfulness INT DEFAULT 0
);
-- review id int references review (review_id) <- for foreign keys

CREATE INDEX reviewIndex ON review (product_id);

COPY review
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/CSVs/reviews.csv'
DELIMITER ','
CSV HEADER;

SELECT setval('review_id_seq', max(id)) FROM review;

----------------------------------------------------------------------
/* Photo Table */
DROP TABLE IF EXISTS reviews_photos;

CREATE TABLE reviews_photos(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id INT REFERENCES review (id),
  url VARCHAR
);

CREATE INDEX reviewIdIndex ON reviews_photos (review_id);

COPY reviews_photos
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/CSVs/reviews_photos.csv'
DELIMITER ','
CSV HEADER;

SELECT setval('reviews_photos_id_seq', max(id)) FROM reviews_photos;


------------------------------------------------------------------------
/* Characteristics Table */
DROP TABLE IF EXISTS characteristics;

CREATE TABLE characteristics(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT REFERENCES review (product_id),
  name VARCHAR
);

CREATE INDEX charIndexes ON characteristics (product_id);

COPY characteristics
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/CSVs/characteristics.csv'
DELIMITER ','
CSV HEADER;

SELECT setval('characteristics_id_seq', max(id)) FROM characteristics;


------------------------------------------------------------------------
/* Meta Table */
DROP TABLE IF EXISTS meta;

CREATE TABLE meta(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  characteristic_id INT REFERENCES characteristics (id),
  review_id INT REFERENCES review (id),
  value INT
);

CREATE INDEX metaIndexes ON meta (characteristic_id, review_id);

COPY meta
FROM '/Users/mitchwintrow/Documents/mrrobotisreal/sdc-project-atelier/CSVs/characteristic_reviews.csv'
DELIMITER ','
CSV HEADER;

SELECT setval('meta_id_seq', max(id)) FROM meta;